#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/ejml-ddense-0.31.jar:$APPDIR/lib/ejml-simple-0.31.jar:$APPDIR/lib/ejml-core-0.31.jar:$APPDIR/lib/ofosho_ledcontroller.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar" ofosho_ledcontroller "$@"
